title: Anusha's Portfolio
description: A personal portfolio to showcase my projects and resume
theme: minima

baseurl: "/anusha.github.io"

header_pages:
  - index.md
  - resume.md
  - projects.md
  - contact.md
