title: Anusha's Portfolio
description: A personal portfolio to showcase my projects and resume
theme: minima

baseurl: ""

header_pages:
  - index.md
  - resume/index.md
  - projects/index.md
  - contact/index.md